# Generated by Django 3.2.25 on 2024-07-11 09:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemname', models.CharField(max_length=24, validators=[django.core.validators.MinLengthValidator(4, 'Error: Der Name kann nur 4 - 24 Zeichen enthalten!')])),
                ('number', models.CharField(max_length=3, validators=[django.core.validators.MinLengthValidator(1, 'Error: Die Anzahl kann nur nur ein- bis dreistellig sein!')])),
            ],
        ),
    ]
